# Generated by Django 6.0.5 on 2026-07-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_song_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='echo_song_title_ecc578_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='echo_song_genre_66e313_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['created_at'], name='echo_song_created_335eca_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
